<?php
require_once 'PHPUnit/Framework.php';

require_once '/Users/olle/opensource/php/File_Launcher/File/Launcher.php';

/**
 * File_Launcher with test-friendly methods.
 */
class File_LauncherFake extends File_Launcher {
    
    public function switchToWindows() {
        $this->nCurrentOS = self::$OS_WINDOWS;
    }
    public function switchToLinux() {
        $this->nCurrentOS = self::$OS_LINUX;
    }
    public function switchToKde() {
        $this->nCurrentDE = self::$DE_LINUX_KDE;
    }
    public function switchToGnome() {
        $this->nCurrentDE = self::$DE_LINUX_GNOME;
    }
    public function switchToMac() {
        $this->nCurrentOS = self::$OS_MAC;
    }
    public function setCurrentDe($de) {
        $this->nCurrentDE = $de;
    }
    
    public function getCommand($strFilename, $bBackground) {
        return parent::getCommand($strFilename, $bBackground);
    }
}


/**
 * Test class for File_Launcher.
 * Generated by PHPUnit on 2010-08-17 at 10:58:54.
 */
class File_LauncherTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var File_Launcher
     */
    protected $launcher;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->launcher = new File_LauncherFake;
    }

    public function testGetCommand()
    {
        $file = 'foo.txt';
        $this->launcher->switchToWindows();
        $this->assertEquals('start "" "foo.txt"', $this->launcher->getCommand($file, true));
        $this->launcher->switchToWindows();
        $this->assertEquals('start "" /WAIT "foo.txt"', $this->launcher->getCommand($file, false));
        
        
        $this->launcher->switchToMac();
        $this->assertEquals('open "foo.txt"', $this->launcher->getCommand($file, true));

        $this->launcher->switchToLinux();

        $this->launcher->switchToKde();
        $this->assertEquals('kfmclient exec "foo.txt"', $this->launcher->getCommand($file, true));

        $this->launcher->switchToGnome();
        $this->assertEquals('gnome-open "foo.txt"', $this->launcher->getCommand($file, true));
    }

}
?>